
name: docs
on:
  push:
    branches: [ main, huangpu, hanryxu ]
  pull_request:
    branches: [ main, huangpu, hanryxu ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DOCS_GP_ACTIONS_DEPLOY_KEY }}
        external_repository: numpygraph/numpygraph.github.io
        publish_branch: main  # default: gh-pages
        publish_dir: ./docs/build/html/

