
name: docs
on:
  push:
    branches: [ main, huangpu, docs]
  pull_request:
    branches: [ main, huangpu, docs]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clone submodule tinydag
      env:
        SSH_KEY_FOR_SUBMODULE: ${{secrets.CLONE_FROM_TINYDAG_SSH_PRIVATE_KEY}}
      run:
        mkdir $HOME/.ssh && echo "$SSH_KEY_FOR_SUBMODULE" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa && git submodule update --init --recursive
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: sphinx-apidoc
      run: |
        cd docs
        # sphinx-apidoc -o source ../numpygraph -f & make html
        make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html

