
name: docs
on:
  push:
    branches: [ main, huangpu, docs]
  pull_request:
    branches: [ main, huangpu, docs]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: sphinx-apidoc
      run: |
        cd docs
        sphinx-apidoc -o source ../numpygraph -f & make html
        make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        keep_files: true
        deploy_key: ${{ secrets.DOCS_GP_ACTIONS_DEPLOY_KEY }}
        external_repository: numpygraph/numpygraph.github.io
        publish_branch: main  # default: gh-pages
        publish_dir: docs/build/html
        cname: numpygraph.org

